matrix:
  include:
    - language: node_js
      node_js:
        - 8.10.0
      install:
        - yarn install
      script:
        - yarn build
    
    - language: php
      php:
        - 7.2.8
      install:
        - composer install
      script:
        - php artisan serve

notifications:
  email: false