matrix:
  include:
    - language: node_js
      node_js:
        - 8.10.0
      install:
        - npm install
      script:
        - npm run production
    
    - language: php
      php:
        - 7.2.8
      install:
        - composer install
      script:
        - phpunit

notifications:
  email: false